### ISSUE TITLE
Missing dnote.yml

### ISSUE THREAD

**Issue by mvz** [rubyworks/dnote#14]
Version 1.7.0 of dnote aborts immediately because it cannot find dnote.yml.

**Comment by jcangas** [comment]
a bit more: a downloaded dnote.yml from github and put in my gems dir, then dnote aborts because constant missing version ... 
Finally I copied the content of .ruby into dnote.tml and all works fine!

**Comment by FlyboyArt** [comment]
Same problem for me and I followed jcangas's recommendation and all works now. Seems like a simple thing to fix...

**Comment by trans** [comment]
Thanks for the report. Sorry it took me so long to get to this. I haven't been getting all issues in my email, but thanks to your report I finally figured out why. So double thanks!

In any case, I just released v1.7.1 to correct this, so it should be fixed now.

**Comment by mvz** [comment]
Thanks! Just installed 1.7.1, and it works flawlessly.
