### ISSUE TITLE
Option to generate report sorted by filename

### ISSUE THREAD

**Issue by taazza** [rubyworks/dnote#2]
At the moment, it defaults & sorts by labels. It would great if u could add the option to sort by filename.

Thx for an awesome tool, its a boon to manage labels & developers!

**Comment by trans** [comment]
Good idea. I will work on this.

**Comment by ghost** [comment]
Just pushed 1.2.0, lots of new formats. Try <code>--file</code> and try <code>-f html/file</code>, for instance. Aso use <code>-T</code> to see all format templates.
