### ISSUE TITLE
--label throws an exception

### ISSUE THREAD

**Issue by taazza** [rubyworks/dnote#3]
dnote --label FIXME generates this error. Could you pls fix it? Thx!

/tmp/test/vendor/gems/gems/dnote-1.1.4/lib/dnote/format.rb:45:in `__send__': undefined method`labels=' for #DNote::Format:0xb79102a0 (NoMethodError)
    from /tmp/test/vendor/gems/gems/dnote-1.1.4/lib/dnote/format.rb:45:in `initialize'
    from /tmp/test/vendor/gems/gems/dnote-1.1.4/lib/dnote/format.rb:44:in`each'
    from /tmp/test/vendor/gems/gems/dnote-1.1.4/lib/dnote/format.rb:44:in `initialize'
    from /tmp/test/vendor/gems/gems/dnote-1.1.4/lib/dnote/command.rb:121:in`new'
    from /tmp/test/vendor/gems/gems/dnote-1.1.4/lib/dnote/command.rb:121:in `run'
    from ../../bin/../vendor/gems/gems/dnote-1.1.4/bin/dnote:3
    from ../../bin/dnote:3:in`load'
    from ../../bin/dnote:3

**Comment by ghost** [comment]
Thanks. It is fixed for next release which should be tonight.

Have something to think about here though. Currently DNote picks up any note that is designated by an all-cap label followed by a colon. The --label option just adds "special" labels that are found even if a colon is not present. But maybe it would be more useful if when a --label option is used it matches ONLY that label?

**Comment by ghost** [comment]
Just pushed 1.2.0. This issue is fixed, and I also made specified labels the only ones returned.
