### ISSUE TITLE
little more free Label patttern

### ISSUE THREAD

**Issue by jcangas** [rubyworks/dnote#7]
Hi: I love Dnote so much I want use it for my other non ruby projects: yes I'm guilty; also write non ruby :(. So I want use other patterns than #LABEL:  what about //LABEL: ? it is valid for java, C, Delphi.
Maybe options --premark --postmark can do the trick, by default :premark => '#' and :postmark => ':'
That's all!. Thanks for the useful Dnote project

**Comment by rubyworks** [comment]
Your wish is my command ;-)

**Comment by jcangas** [comment]
Wow!! ... so quickly .... thanks a lot !!

**Comment by ghost** [comment]
No problem. It wasn't a hard to get basic marker support in there. Let me know if you run into any issues.
