### ISSUE TITLE
Error running dnote over a rails project

### ISSUE THREAD

**Issue by juanjo** [rubyworks/dnote#8]
$ dnote -T
/Library/Ruby/Gems/1.8/gems/dnote-1.3.0/lib/dnote/session.rb:224: warning: don't put space before argument parentheses
undefined method `group_by' for #Array:0x1123b34

**Comment by ghost** [comment]
Thank you! Fix will be in next release (in a day or two).

**Comment by trans** [comment]
I noticed a new issue with `dnote -T` akin to this one and just fixed it, so I'll will add this issue to the current milestone and close it.
