### ISSUE TITLE
source capture

### ISSUE THREAD

**Issue by jcangas** [rubyworks/dnote#9]
I thing vert useful to cature some source lines for show in dnote report, i.e. copy some lines _after_ the note. Sample
      # FIXME: the count is incorrect
    def counts
      @counts ||= (
        h = {}
        by_label.each do |label, notes|
          h[label] = notes.size
        end
        h
      )
    end

Then the report shows something likes
  FIXME: the count is incorrect
    def counts
      @counts ||= (
        h = {}
        by_label.each do |label, notes| 
    ...

The number of lines to capture can be a parameter.

**Comment by trans** [comment]
This will be in version 1.6.0 release which should go out today.
